osu-wine rewrite + launch opts.

diff --git a/osu-wine b/osu-wine
--- a/osu-wine
+++ b/osu-wine
@@ -1,18 +1,12 @@
 #!/usr/bin/env bash
-Info()
-{
-    echo -e '\033[1;34m'"Winello:\033[0m $*";
-}
-
-Error()
-{  
-    echo -e '\033[1;31m'"Script failed:\033[0m $*"; exit 1;
-}
 
 ## Welcome to your osu! launch script!
 ## Most stuff here is explained with comments, but if you just need to add
-## something to osu (example: adding gamemode) see line ~94, you'll find the osu! launcher there.
+## any argument to osu!, use #LAUNCH_ARGS!
 
+## If you ever need to change something to the osu! launcher besides args, just go to line ~68
+
+export LAUNCH_ARGS="" # Use this for args like prime-run or gamemoderun!
 export WINEESYNC=1 # Enables esync (when possible)
 export WINEFSYNC=1 # Enables fsync (when possible)
 export WINE_BLOCK_GET_VERSION=1 # Hides wine ver. thanks to oglfreak's patch
@@ -25,8 +19,15 @@ export vblank_mode=0            # Disables vsync for mesa
 export __GL_SYNC_TO_VBLANK=0    # Disables vsync for NVIDIA >=510
 export WINEDLLOVERRIDES=winemenubuilder.exe=d# # Blocks wine from creating .desktop files
 
-Help()
-{
+function Info(){
+    echo -e '\033[1;34m'"Winello:\033[0m $*";
+}
+
+function Error(){
+    echo -e '\033[1;31m'"Script failed:\033[0m $*"; exit 1;
+}
+
+function Help(){
     Info "Script features:
     osu-wine: Runs osu!
     osu-wine --winecfg : Runs winecfg on the osu! Wineprefix
@@ -46,84 +47,89 @@ Help()
     osu-wine --fixsteamdeck: Reinstalls game dependencies after SteamOS updates"
 }
 
-Checkshort()
-{
+function Checkshort(){      # Deletes useless shortcuts created when installing
     if [ -e "$HOME/.local/share/applications/wine/Programs/osu!.desktop" ] ; then
-    rm -f "$HOME/.local/share/applications/wine/Programs/osu!.desktop" ; fi
+        rm -f "$HOME/.local/share/applications/wine/Programs/osu!.desktop" ; fi
 
     DESKTOPDIR=$(xdg-user-dir DESKTOP)
     if [ -e "$DESKTOPDIR/osu!.lnk" ] ; then
-    rm -f "$DESKTOPDIR/osu!.lnk" ; fi
+        rm -f "$DESKTOPDIR/osu!.lnk" ; fi
 }
 
-Update()
-{
+function Update(){
     git -C "$HOME/.local/share/osuconfig/update" pull --quiet
     bash "/$HOME/.local/share/osuconfig/update/osu-winello.sh" update
 }
 
+
 case "$1" in
+
     '')
-	wine "$OSUPATH/osu!.exe" #osu! launcher
-	Checkshort
-	;;
+    $LAUNCH_ARGS wine "$OSUPATH/osu!.exe" #osu! launcher
+    Checkshort
+    ;;
 
     '--devserver')
-    wine "$OSUPATH/osu!.exe" -devserver "$2" #osu! launcher with specified devserver
-    Checkshort
+    $LAUNCH_ARGS wine "$OSUPATH/osu!.exe" -devserver "$2" #osu! launcher with specified devserver
     ;;
 
     '--regedit')
     regedit
     ;;
 
-  	'--winecfg')
+    '--winecfg')
     winecfg
-	;;
+    ;;
 
-	'--winetricks')
-	winetricks "${@:2}"
-	;;
+    '--winetricks')
+    winetricks "${@:2}"
+    ;;
 
     '--changedir')
+    function deleteFolder(){
+        Info "Do you want to delete the previous install?"
+        read -r -p "$(Info "Choose your option (y/n): ")" dirchoice
+
+            if [ "$dirchoice" = 'y' ] || [ "$dirchoice" = 'Y' ]; then
+                read -r -p "$(Info "Are you sure? This will delete your files! (y/n)")" dirchoice2
+
+                    if [ "$dirchoice2" = 'y' ] || [ "$dirchoice2" = 'Y' ]; then
+                        lastdir=$(</"$HOME/.local/share/osuconfig/osupath")
+                        rm -rf "$lastdir/osu!" && Info "Cleaning done!"  
+                    else 
+                        Info "Skipping..."
+                    fi
+
+            else
+                Info "Skipping.." 
+            fi 
+    }
+    
     Info "Please choose your new directory:"
 
     newdir="$(zenity --file-selection --directory)"
     lastdir=$(</"$HOME/.local/share/osuconfig/osupath")
-    rm -f "$HOME/.local/share/osuconfig/osupath"
 
+    rm -f "$HOME/.local/share/osuconfig/osupath"
     if [ -d "$newdir/osu!" ] || [ -s "$newdir/osu!.exe" ]; then
         Info "osu! folder/game already exists: skipping.."
 
-    if [ -d "$newdir/osu!" ]; then
-        OSUPATH="$newdir/osu!"
-        echo "$OSUPATH" > "$HOME/.local/share/osuconfig/osupath"
+        if [ -d "$newdir/osu!" ]; then
+            OSUPATH="$newdir/osu!"
+            echo "$OSUPATH" > "$HOME/.local/share/osuconfig/osupath"
 
-    Info "Change done from '$lastdir' to '$newdir'!"
+            Info "Change done from '$lastdir' to '$newdir'!"
+            deleteFolder
+        fi
 
-    Info "Do you want to delete the previous install?"
-    read -r -p "$(Info "Choose your option (y/n): ")" dirchoice
-    if [ "$dirchoice" = 'y' ] || [ "$dirchoice" = 'Y' ]; then
-        read -r -p "$(Info "Are you sure? This will delete your files! (y/n)")" dirchoice2
-        if [ "$dirchoice2" = 'y' ] || [ "$dirchoice2" = 'Y' ]; then
-        rm -rf "$lastdir/osu!" && Info "Cleaning done!" ; else Info "Skipping..." ; fi
-    else
-        Info "Skipping.." ; fi ; fi
+        if [ -s "$newdir/osu!.exe" ]; then
+            OSUPATH="$newdir"
+            echo "$OSUPATH" > "$HOME/.local/share/osuconfig/osupath"
 
-    if [ -s "$newdir/osu!.exe" ]; then
-        OSUPATH="$newdir"
-        echo "$OSUPATH" > "$HOME/.local/share/osuconfig/osupath"
+            Info "Change done from '$lastdir' to '$newdir'!"
+            deleteFolder
+        fi
 
-    Info "Change done from '$lastdir' to '$newdir'!"
-
-    Info "Do you want to delete the previous install?"
-    read -r -p "$(Info "Choose your option (y/n): ")" dirchoice
-    if [ "$dirchoice" = 'y' ] || [ "$dirchoice" = 'Y' ]; then
-        read -r -p "$(Info "Are you sure? This will delete your files! (y/n)")" dirchoice2
-        if [ "$dirchoice2" = 'y' ] || [ "$dirchoice2" = 'Y' ]; then
-            rm -rf "$lastdir/osu!" && Info "Cleaning done!" ; else Info "Skipping..." ; fi
-        else
-            Info "Skipping.." ; fi ; fi
     else
         mkdir "$newdir/osu!"
         OSUPATH="$newdir/osu!"
@@ -137,16 +143,8 @@ case "$1" in
             wget --no-check-certificate -O "$OSUPATH/osu!.exe" "http://m1.ppy.sh/r/osu!install.exe" ; fi
 
         Info "Change done from '$lastdir' to '$newdir'!"
-
-        Info "Do you want to delete the previous install?"
-        read -r -p "$(Info "Choose your option (y/n): ")" dirchoice
-        if [ "$dirchoice" = 'y' ] || [ "$dirchoice" = 'Y' ]; then
-            read -r -p "$(Info "Are you sure? This will delete your files! (y/n)")" dirchoice2
-            if [ "$dirchoice2" = 'y' ] || [ "$dirchoice2" = 'Y' ]; then
-                rm -rf "$lastdir/osu!" && Info "Cleaning done!" ; else Info "Skipping..." ; fi
-            else
-                Info "Skipping.." ; fi
-        fi
+        deleteFolder
+    fi
     ;;
 
     '--remove')
@@ -161,14 +159,14 @@ case "$1" in
     wineserver -k9
     ;;
 
-	'--update')
-	Update
-	;;
-    
+    '--update')
+    Update
+    ;;
+
     '--fixsteamdeck')
-    
+    # Reading the OS id..
     osid=$(grep -oP '(?<=^ID=).+' /etc/os-release | tr -d '"')
-    
+
     # Checking for 'sudo' or 'doas'        
     root_var="sudo"
     if command -v doas >/dev/null 2>&1 ; then
@@ -177,7 +175,7 @@ case "$1" in
             root_var="doas"
         fi
     fi
-
+    
     if [ "$osid" != "steamos" ] ; then
         Error "Your PC isn't really a Steam Deck, no need to use this c.c"
     
@@ -194,45 +192,50 @@ case "$1" in
 
     '--lutris')
     if [ -d "$HOME/.local/share/lutris" ]; then
-      Info "Lutris was found, do you want to copy wine-osu there? (y/n)"
-      read -r -p "$(Info "Choose your option: ")" lutrischoice
+        Info "Lutris was found, do you want to copy wine-osu there? (y/n)"
+        read -r -p "$(Info "Choose your option: ")" lutrischoice
         if [ "$lutrischoice" = 'y' ] || [ "$lutrischoice" = 'Y' ]; then
-
             mkdir -p "$HOME/.local/share/lutris/runners/wine"
+            
             if [ -d "$HOME/.local/share/lutris/runners/wine/wine-osu" ]; then
                 Info "wine-osu is already installed in Lutris, skipping..."
             else
                 cp -r "$HOME/.local/share/osuconfig/wine-osu" "$HOME/.local/share/lutris/runners/wine" 
                 rm -rf "$HOME/.local/share/lutris/runners/wine/wine-osu/share/wine/fonts"
-                ln -s "$HOME/.local/share/osuconfig/W10Fonts" "$HOME/.local/share/lutris/runners/wine/wine-osu/share/wine/fonts" ; fi
+                ln -s "$HOME/.local/share/osuconfig/W10Fonts" "$HOME/.local/share/lutris/runners/wine/wine-osu/share/wine/fonts"
+            fi
 
             if [ -d "$HOME/.var/app/net.lutris.Lutris/data/lutris" ]; then
                 mkdir -p "$HOME/.var/app/net.lutris.Lutris/data/lutris/runners/wine"
+                
                 if [ -d "$HOME/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-osu" ]; then
-                  Info "wine-osu is already installed in Flatpak Lutris, skipping..."
+                    Info "wine-osu is already installed in Flatpak Lutris, skipping..."
                 else
-                  cp -r "$HOME/.local/share/osuconfig/wine-osu" "$HOME/.var/app/net.lutris.Lutris/data/lutris/runners/wine" 
-                  rm -rf "$HOME/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-osu/share/wine/fonts"
-                  ln -s "$HOME/.local/share/osuconfig/W10Fonts" "$HOME/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-osu/share/wine/fonts"; fi
+                    cp -r "$HOME/.local/share/osuconfig/wine-osu" "$HOME/.var/app/net.lutris.Lutris/data/lutris/runners/wine" 
+                    rm -rf "$HOME/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-osu/share/wine/fonts"
+                    ln -s "$HOME/.local/share/osuconfig/W10Fonts" "$HOME/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-osu/share/wine/fonts"
+                fi
             fi
-
-        else
-          Info "Lutris not detected; if you installed it, launch it at least once." ; fi
+        fi
+    else
+        Info "Lutris not detected; if you installed it, launch it at least once."
     fi
 
     if [ -d "$HOME/.var/app/net.lutris.Lutris/data/lutris" ] && [ ! -d "$HOME/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-osu" ]; then
-      Info "Flatpak Lutris was found, do you want to copy wine-osu there? (y/n)"
-      read -r -p "$(Info "Choose your option: ")" lutrischoice2
-        if [ "$lutrischoice2" = 'y' ] || [ "$lutrischoice2" = 'Y' ]; then
+        Info "Flatpak Lutris was found, do you want to copy wine-osu there? (y/n)"
+        read -r -p "$(Info "Choose your option: ")" lutrischoice2
+            if [ "$lutrischoice2" = 'y' ] || [ "$lutrischoice2" = 'Y' ]; then
         
-          mkdir -p "$HOME/.var/app/net.lutris.Lutris/data/lutris/runners/wine"
-          if [ -d "$HOME/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-osu" ]; then
-              Info "wine-osu is already installed in Flatpak Lutris, skipping..."
-          else
-              cp -r "$HOME/.local/share/osuconfig/wine-osu" "$HOME/.var/app/net.lutris.Lutris/data/lutris/runners/wine" 
-              rm -rf "$HOME/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-osu/share/wine/fonts"
-              ln -s "$HOME/.local/share/osuconfig/W10Fonts" "$HOME/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-osu/share/wine/fonts" ; fi
-        fi
+                mkdir -p "$HOME/.var/app/net.lutris.Lutris/data/lutris/runners/wine"
+                if [ -d "$HOME/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-osu" ]; then
+                    Info "wine-osu is already installed in Flatpak Lutris, skipping..."
+                
+                else
+                    cp -r "$HOME/.local/share/osuconfig/wine-osu" "$HOME/.var/app/net.lutris.Lutris/data/lutris/runners/wine" 
+                    rm -rf "$HOME/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-osu/share/wine/fonts"
+                    ln -s "$HOME/.local/share/osuconfig/W10Fonts" "$HOME/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-osu/share/wine/fonts" 
+                fi
+            fi
     fi
  
     if [ -d "$HOME/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-osu" ] || [ -d "$HOME/.local/share/lutris/runners/wine/wine-osu" ]; then
@@ -265,7 +268,6 @@ case "$1" in
     WINEPREFIX="$HOME/.local/share/wineprefixes/osu-wineprefix" wine reg delete "HKEY_CLASSES_ROOT\folder\shell\open\ddeexec" /f
     WINEPREFIX="$HOME/.local/share/wineprefixes/osu-wineprefix" wine reg add "HKEY_CLASSES_ROOT\folder\shell\open\command" /f /ve /t REG_SZ /d "/home/$USER/.local/share/osuconfig/folderfixosu xdg-open \"%1\""
     ;;
-
 
     '--w10fonts')
     git -C "$HOME/.local/share/osuconfig/update" pull --quiet
@@ -307,18 +309,16 @@ case "$1" in
     Wineprefix location: $WINEPREFIX
     osu! folder: '$OSUPATH'
 
-    If you need to add more options to osu!, see around line 86 of the script (ex. nano ~/.local/bin/osu-wine)
-
-    You can run 'osu-wine help' to see all the script's functions (fix prefix, w10 fonts etc.)
+    If you need to add more options to osu!, see around line 68 of the script (ex. nano ~/.local/bin/osu-wine)
+    You can run 'osu-wine --help' to see all the script's functions (fix prefix, w10 fonts etc.)
     You can find more troubleshooting and info at here: https://osu.ppy.sh/community/forums/topics/1248084?n=1"
     ;;
-
-	'help')
-	Help
-	;;
 
     '--help')
     Help
     ;;
 
+    'help')
+    Help
+    ;;
 esac
