osu-wine: clean up a bit more

diff --git a/osu-wine b/osu-wine
--- a/osu-wine
+++ b/osu-wine
@@ -80,23 +80,6 @@ export OSUPATH
 # Helper functions for the launcher script
 ###################################################################################################
 
-Info() {
-    echo -e '\033[1;34m'"Winello:\033[0m $*"
-}
-
-Warning() {
-    echo -e '\033[0;33m'"Winello:\033[0m $*"
-}
-
-Error() {
-    echo -e '\033[1;31m'"Winello (error):\033[0m $*"
-}
-
-ErrorAndExit() {
-    echo -e '\033[1;31m'"Script failed:\033[0m $*"
-    exit 1
-}
-
 Help() {
     Info "Script features:
     osu-wine: Runs osu!
@@ -124,11 +107,10 @@ Help() {
 }
 
 # Won't return failure if there's no internet connection, but tries to update the main script first before calling the function
-cleanUpdateFolder() {
+MainScriptUpdate() {
     _clone() { GIT_TERMINAL_PROMPT=0 git clone "https://github.com/NelloKudo/osu-winello.git" "$XDG_DATA_HOME/osuconfig/update" --quiet 2>/dev/null; }
     _pull() { GIT_TERMINAL_PROMPT=0 git -C "$XDG_DATA_HOME/osuconfig/update" pull --quiet 2>/dev/null; }
     _reset() { GIT_TERMINAL_PROMPT=0 git -C "$XDG_DATA_HOME/osuconfig/update" reset --hard "${1:-HEAD}" --quiet 2>/dev/null; }
-
     if [ ! -d "$XDG_DATA_HOME/osuconfig/update" ]; then
         _clone # where did the update directory go? need to clone it first.
     else
@@ -136,12 +118,7 @@ cleanUpdateFolder() {
     fi
     _reset
     # check again, doesn't hurt
-    [ ! -d "$XDG_DATA_HOME/osuconfig/update" ] && return 1
-    return 0
-}
-
-MainScriptUpdate() {
-    cleanUpdateFolder || ErrorAndExit "Your osu-winello folder is broken, please reinstall from scratch..."
+    [ -d "$XDG_DATA_HOME/osuconfig/update" ] || ErrorAndExit "Your osu-winello folder is broken, please reinstall from scratch..."
     MainScript "${*}"
     return $?
 }
@@ -183,6 +160,23 @@ LaunchOsu() {
     export WINEDEBUG="+timestamp,+pid,+tid,+threadname,+debugstr,+loaddll,+winebrowser,+exec ${WINEDEBUG:-}"
     exec "${PRE_ARGS[@]}" "${WINE}" "${OSU_EXE[@]}" "${POST_ARGS[@]}" &>"${WINELLO_LOGS_PATH}" || return 1
     return 0
+}
+
+Info() {
+    echo -e '\033[1;34m'"Winello:\033[0m $*"
+}
+
+Warning() {
+    echo -e '\033[0;33m'"Winello:\033[0m $*"
+}
+
+Error() {
+    echo -e '\033[1;31m'"Winello (error):\033[0m $*"
+}
+
+ErrorAndExit() {
+    echo -e '\033[1;31m'"Script failed:\033[0m $*"
+    exit 1
 }
 
 ###################################################################################################
